[package]
name = "game_labs"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
#bevy = "0.14.1"
rand = "0.8.5"
bevy = { version = "0.14.1", features = ["bevy_render", "dynamic_linking"] }
